from __future__ import annotations

from tony.core.command_parser import ParsedCommand


class Planner:
    def describe_action(self, parsed: ParsedCommand) -> str:
        descriptions = {
            "open_vscode": "Open the current folder in VS Code.",
            "open_folder": "Open the current folder.",
            "run_shell_command": f"Run shell command: {parsed.argument or parsed.original_text}",
            "git_status": "Run git status.",
            "git_diff": "Show git diff.",
            "git_commit": "Create a git commit.",
            "git_push": "Push commits to the remote repository.",
            "analyze_project": "Check git status, recent log, and project files for obvious issues.",
            "create_file": "Create or edit a file.",
            "read_file": "Read a local file.",
            "summarize": "Summarize the provided text with the local Ollama model.",
            "open_app": "Open a safe local app.",
            "open_terminal": "Open a terminal in the current workspace.",
            "open_file_explorer": "Open File Explorer in the current workspace.",
            "set_workspace": "Set the active Tony workspace.",
            "run_project": "Run the detected project command.",
            "run_tests": "Run the detected project test command.",
            "install_dependencies": "Install project dependencies.",
            "open_localhost": "Open localhost in the browser.",
            "take_screenshot": "Take a local screenshot.",
            "check_running_processes": "Show a short running process list.",
            "start_live_voice": "Start optional live voice mode.",
            "stop_live_voice": "Stop live voice mode.",
            "enable_wake_mode": "Enable optional wake mode.",
            "disable_wake_mode": "Disable wake mode.",
            "start_screen_recording": "Start local screen recording.",
            "stop_screen_recording": "Stop local screen recording.",
            "start_action_recording": "Start local action recording.",
            "stop_action_recording": "Stop local action recording.",
            "stop_recording": "Stop active recordings.",
            "replay_macro": "Replay the last recorded macro.",
            "show_audio_settings": "Show microphone and voice settings.",
            "open_recordings_folder": "Open local recordings folder.",
            "analyze_repo": "Analyze the repository locally.",
            "analyze_code": "Scan code and suggest improvements.",
            "explain_error": "Explain an error in simple words.",
            "suggest_fix": "Suggest a fix without editing files.",
            "generate_commit_message": "Generate a commit message draft.",
            "github_status": "Show GitHub CLI/repo status.",
            "list_issues": "List GitHub issues.",
            "list_prs": "List GitHub pull requests.",
            "create_issue": "Create a GitHub issue.",
            "create_pr": "Create a GitHub pull request.",
            "generate_client_message": "Generate an editable client message draft.",
            "generate_delivery_note": "Generate a delivery note draft.",
            "generate_report": "Generate a local report.",
            "create_daily_plan": "Create a daily work plan.",
            "add_task": "Add a local task.",
            "list_tasks": "List local tasks.",
            "complete_task": "Mark a local task done.",
            "generate_codex_prompt": "Generate a prompt for an AI coding tool.",
            "run_workflow": "Run a safe predefined workflow.",
            "unknown": "Ask the local Ollama model for help understanding the command.",
        }
        return descriptions.get(parsed.intent, "Handle user command.")
